#!/bin/bash
set -ex

echo "Running test for self-contained .NET Hello World app"

(cd src && dotnet publish --self-contained -r linux-x64)

docker run --rm -v "$PWD/src:/app:ro" \
    ubuntu/dotnet-deps:test exec \
    /app/bin/Release/net8.0/linux-x64/Hello
