#!/bin/bash

set -ex

IMAGE_NAME="$1"
IMAGE_VERSION="$2"
ROCK_PATH="$3"

/snap/rockcraft/current/bin/skopeo copy --insecure-policy \
    oci-archive:"$ROCK_PATH" \
    docker-daemon:"$IMAGE_NAME:$IMAGE_VERSION"

if [ -f "$IMAGE_NAME/run-test" ]; then
    "$IMAGE_NAME/run-test" "$IMAGE_VERSION"
fi
