#!/bin/bash

set -ex

IMAGE_VERSION="$1"

echo "Testing image dotnet-aspnet:$IMAGE_VERSION"

docker run --rm "dotnet-aspnet:$IMAGE_VERSION" exec dotnet --info | grep \
    "Microsoft.AspNetCore.App $IMAGE_VERSION"
